DROP POLICY IF EXISTS users_own ON forma.users;
DROP POLICY IF EXISTS profiles_own ON forma.profiles;
DROP POLICY IF EXISTS goals_own ON forma.goals;
DROP POLICY IF EXISTS foods_visible ON forma.foods;
DROP POLICY IF EXISTS foods_owned_write ON forma.foods;
DROP POLICY IF EXISTS food_logs_own ON forma.food_logs;
DROP POLICY IF EXISTS favorites_own ON forma.favorite_foods;
DROP POLICY IF EXISTS weights_own ON forma.weight_logs;
DROP POLICY IF EXISTS routines_own ON forma.routines;
DROP POLICY IF EXISTS workouts_own ON forma.workouts;
DROP POLICY IF EXISTS receipts_own ON forma.mutation_receipts;
CREATE POLICY users_own ON forma.users USING (id=(select auth.uid())) WITH CHECK (id=(select auth.uid()));
CREATE POLICY profiles_own ON forma.profiles USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY goals_own ON forma.goals USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY foods_read ON forma.foods FOR SELECT USING (owner_id IS NULL OR owner_id=(select auth.uid()));
CREATE POLICY foods_insert ON forma.foods FOR INSERT WITH CHECK (owner_id=(select auth.uid()));
CREATE POLICY foods_update ON forma.foods FOR UPDATE USING (owner_id=(select auth.uid())) WITH CHECK (owner_id=(select auth.uid()));
CREATE POLICY foods_delete ON forma.foods FOR DELETE USING (owner_id=(select auth.uid()));
CREATE POLICY food_logs_own ON forma.food_logs USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY favorites_own ON forma.favorite_foods USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY weights_own ON forma.weight_logs USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY routines_own ON forma.routines USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY workouts_own ON forma.workouts USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE POLICY receipts_own ON forma.mutation_receipts USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
CREATE INDEX IF NOT EXISTS favorite_foods_food_id_idx ON forma.favorite_foods(food_id);
CREATE INDEX IF NOT EXISTS food_logs_food_id_idx ON forma.food_logs(food_id);
